var first_list = [
	"Il en r\351sulte",
	"On perçoit alors",
	"On peut alors imaginer",
	"Nous en retenons",
	"Nous sommes tace \340",
	"Nous en retiendrons",
	"L'artiste d\351finit",
	"L'artiste pense donc",
	"L'artiste saisit ainsi",
	"L'artiste transcende",
	"L'artiste exprime",
	"L'artiste transgresse",
	"L'artiste dilate alors",
	"L'artiste trace ainsi",
	"L'artiste imagine alors",
	"L'artiste \351voque",
	"L'artiste revisite",
	"L'artiste vit alors",
	"L'artiste invente alors",
	"L'artiste exprime ainsi",
	"L artiste dessine",
	"Ainnsi se transforme",
	"L artiste fragmente",
	"L'artiste affirme alors",
	"L'artiste r\351v\350le",
	"L'artiste r\351alise ainsi",
	"L'artiste \351puise alors",
	"Se d\351tache donc",
	"L'artiste d\351ploie donc",
	"Cela nous r\351v\350le",
	"Cela implique",
	"Cela d\351clenche",
	"Cela fait \351cho \340",
	"Cela d\351finit un",
	"Cela am\350ne vers",
	"Cola absout ainsi",
	"Cela dilate alors",
	"Cela sugg\350re",
	"Cela dissimule",
	"Celles-ci sombrent dans",
	"Celles-ci nous \351voquent",
	"Celles-ci distillent",
	"Celles-ci font place \340",
	"Celles-ci r\351pondent \340",
	"Celles-ci parlent d'",
	"Celles-ci font \351chos \340",
	"Celles-ci absorbent",
	"Celles-ci contaminent",
	"Celles-ci cachent"
];

var second_list = [
	"une tension",
	"une vanit\351",
	"une exp\351riencc",
	"une composition",
	"une existence",
	"une op\351ration",
	"une illusion",
	"une Sp\351cificit\351",
	"une m\351moire",
	"une pratique",
	"une utilisation",
	"une mise en jeu",
	"une limite",
	"une typologie",
	"une iconographie",
	"une mise en scone",
	"une fiction",
	"une action",
	"une saturation",
	"une exploration",
	"une caract\351ristique",
	"une s\351lection",
	"une torme",
	"une dimension",
	"une violence",
	"une surimpression",
	"une pr\351occupation",
	"une image",
	"une rationalisation",
	"une dissociation",
	"une mise en acte",
	"une projection",
	"une d\351flagration",
	"une logique",
	"une dégradation",
	"une promenade",
	"une collection",
	"une sc\351nographie",
	"une mise en abime",
	"une disparition",
	"une rupture",
	"une notion",
	"une reproduction",
	"une nature",
	"une s\351lection",
	"une utopie",
	"une infiltration",
	"une v\351g\351tation",
	"une pr\351sence"
];



var third_list = [
	"nouvelle",
	"chim\351rique",
	"principale",
	"premi\350re",
	"possible",
	"quotidienne",
	"perp\351tuelle",
	"formelle",
	"fragile",
	"transgressive",
	"incessante",
	"\351trange",
	"architecturale",
	"multiple",
	"singuli\350re",
	"imaginaire",
	"inhabituelle",
	"th\351orique",
	"volatile",
	"\351ph\351m\350re",
	"radicale",
	"unitaire",
	"triste",
	"instable",
	"circulaire",
	"spectrale",
	"cyclique",
	"fonctionnelle",
	"violente",
	"incertaine",
	"dissonante",
	"mythologique",
	"transparente",
	"originelle.",
	"simple",
	"conceptuelle",
	"polyvalente",
	"harmonieuse",
	"modulable",
	"ergonomique",
	"tormelle",
	"picturale",
	"logique",
	"\351mergente",
	"inerte",
	"symbolique",
	"aride",
	"logique",
	"ultime",
];

var fourth_list = [
	"entre le",
	"\340 travers le",
	"dans le",
	"suivant le",
	"sur le",
	"malgr\351 le",
	"selon le",
	"par le",
	"d\351plaçant le",
	"fragmentant le",
	"caract\351risant le",
	"d\351truisant le",
	"r\351veillant le",
	"mettant en cause le",
	"ouvrant le",
	"contaminant le",
	"stimulant le",
	"concevant le",
	"activant le",
	"dessinant le",
	"exploitant le",
	"cherchant le",
	"imaginant le",
	"supposant le",
	"lib\351rant le",
	"consid\351rant le",
	"incarnant le",
	"qui se veut le",
	"qui pourra \352tre le",
	"qui explorera le",
	"qui \351voquera le",
	"qui d\351voilera le",
	"qui interrogera le",
	"qui questionnera le",
	"qui dissimulera le",
	"qui d\351limitera le",
	"qui transfigurera le",
	"qui r\351v\351lera le",
	"qui captera le",
	"qui cernera le",
	"qui \351voquera le",
	"qui Saisira le",
	"qui d\351place le",
	"qui diffusera le",
	"qui enregistre le",
	"qui fait surgir le",
	"qui habite le",
	"qui dit le",
	"qui d\351truit le",
];

var fifth_list = [
	"statut",
	"paysage",
	"point de fuite",
	"langage",
	"ph\351nom\350ne",
	"territoire",
	"plan",
	"patrimoine",
	"syst\350me",
	"corps",
	"m\351dium",
	"d\351placement",
	"r\351sidu",
	"mat\351riau",
	"r\351sultat",
	"t\351moignage",
	"document",
	"visage",
	"d\351sir",
	"for mat",
	"vide",
	"sens",
	"parcours",
	"principe",
	"signe",
	"cadrage",
	"processus",
	"geste",
	"hors-champ",
	"motif",
	"lien",
	"choc",
	"dessin",
	"texte",
	"tissage",
	"vocabulaire",
	"r\351seau",
	"d\351tail",
	"texte",
	"champ",
	"signifiant",
	"sc\351nar",
	"montage",
	"temps",
	"rep\350re",
	"sujet",
	"paradoxe",
	"rituel "
];


function get_new_phrase() {
	return get_rnd_val(first_list) 
		+ " " 
		+ get_rnd_val(second_list)
		+ " "
		+ get_rnd_val(third_list)
		+ " "
		+ get_rnd_val(fourth_list)
		+ " "
		+ get_rnd_val(fifth_list)
		+ ".";
}

function get_rnd_val(coll) {
	return coll[~~(Math.random() * coll.length)];
}

function write_new_text() {
	var elem = document.getElementById('wow');

	elem.innerHTML = get_new_phrase();
}