// Génère docs/specs.md depuis config.js : node tools/specs.js > docs/specs.md
const fs=require('fs'),path=require('path'),vm=require('vm');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','config.js'),'utf8'),ctx);
const C=ctx.window.GAME_CONFIG,R=C.regles,D=R.degats,F=R.fatigue,PL=R.positionsLancement||{},MO=R.modificateurs||{};
const STATS=['pv','attP','defP','attM','defM','vit'];
const ELS=Object.keys(C.elements).filter(e=>e!==R.elementNeutre);
const sgn=v=>v>0?'+'+v:String(v);
const mods=m=>Object.entries(m||{}).filter(([,v])=>v).map(([k,v])=>`${C.stats[k]} ${sgn(v)}`).join(', ')||'—';
const aff=(a,d)=>a===R.elementNeutre?1:(C.elements[a].bat||[]).includes(d)?2:(C.elements[d].bat||[]).includes(a)?.5:1;
const tbl=(h,rows)=>`| ${h.join(' | ')} |\n|${h.map(()=>' --- ').join('|')}|\n`+rows.map(r=>`| ${r.join(' | ')} |`).join('\n')+'\n';
const owners=id=>Object.entries(C.classes).filter(([,c])=>c.movePool.includes(id)).map(([n])=>n);
const L=R.cases[R.tailleTerrain];
const dots=list=>L.map(l=>list.includes(l)?'■':'□').join('');
const cible=M=>{const c=C.ciblages[M.cible];return c.cases?`${dots(c.cases)} ${c.nom}`:c.nom};
const fx=M=>(M.effets||[]).map(f=>({soin:`soigne ${f.montant}`,regeneration:`soigne ${f.montant} au début des ${f.tours} prochains tours`,racines:`racines (${f.tours} tour)`,drain:`draine ${Math.round(f.ratio*100)} %`,contrecoup:`contrecoup ${f.montant}`,pousser:`pousse de ${f.cases}`,tirer:`tire de ${f.cases}`,echangerCibles:'échange les deux cases visées',defense:`Déf P/M +${f.bonus} (${f.tours} tour)${f.inamovible?', inamovible':''}`,deplacerSoi:`se déplace (${f.direction})`,modStats:`${f.sur} : ${mods(f.stats)}${f.tours!=null?` (${f.tours} tour)`:' jusqu’au banc'}`}[f.type]||f.type)).join(' ; ')||'—';
const accFx=A=>(A.effets||[]).map(f=>({survie:`survit à 1 PV (${f.utilisations}×, si PV ≥ ${f.seuilPV*100} %)`,antiRacines:`annule Racines (${f.utilisations}×)`,verrouChoix:'bloqué sur sa 1re attaque jusqu’à sa sortie',rage:`+${f.bonusDegats} dégât par coup, −${f.coutPV} PV par attaque`,soinFinDeTour:`+${f.montant} PV en fin de tour`,antiBaisse:`annule une baisse de stats (${f.utilisations}×)`}[f.type]||f.type)).join(' ; ')||'—';
const moveRows=ids=>ids.map(id=>{const M=C.attaques[id];return [`**${M.nom}**`,M.element,owners(id).join(', ')||'universel',M.puissance||'—',M.priorite?sgn(M.priorite):'—',cible(M),M.depuis&&M.depuis.length?`${dots(M.depuis)} ${M.depuis.join(', ')}`:'toutes',fx(M)]});
let o=`# Spécifications du prototype\n\n> Généré automatiquement depuis \`config.js\` (\`node tools/specs.js > docs/specs.md\`). Ne pas modifier à la main.\n> Schémas de cases : ■ = case concernée, ordre ${L.join(' → ')}.\n\n`;
o+=`## Règles\n\n`;
o+=`- **Équipe** : ${R.tailleTerrain} sur le terrain, ${R.tailleBanc} au banc (caché), ${R.attaquesParPerso} attaques par perso${R.maxParClasse?`, ${R.maxParClasse} exemplaire(s) max par classe`:''}.\n`;
o+=`- **Tour** : chaque joueur choisit en secret un perso et une attaque, ou un switch. Résolution par priorité, puis Vitesse, puis départage (${R.departage}).\n`;
o+=`- **Dégâts** = max(${D.minimum}, (Puissance${D.bonusElementActif?` + ${D.bonusElement} si même élément que l’équipement`:''} + Attaque − Défense) × affinité)${D.bonusFatigueActif?` + ${D.bonusFatigue} si la cible est fatiguée`:''}. Affinité ×${D.multAvantage} / ÷${D.divDesavantage} (arrondi ${D.arrondi}). Attaque et Défense selon le canal. Une case visée plusieurs fois = plusieurs coups.\n`;
o+=`- **Fatigue** : ${F.active?`le perso qui a agi n’a que le move pool universel au tour suivant (seuil : ${F.minPersosDebout} perso(s) debout). Switch fatiguant : ${F.switchFatigue?'oui':'non'}. Banc efface la fatigue : ${F.bancEfface?'oui':'non'}.`:'désactivée.'}\n`;
o+=`- **Switch** : ${R.switch.actif?`priorité ${R.switch.priorite}, le premier du banc prend la case du sortant. Bloqué par Racines : ${R.switch.bloqueParRacines?'oui':'non'}.`:'désactivé.'}\n`;
o+=`- **K.O.** : remplacement automatique ${R.remplacementAuto?'oui':'non'} ; plateau rétrécissant ${R.plateauRetrecit?'oui':'non'} ; limite de tours ${R.limiteTours||'aucune'}.\n`;
o+=`- **Positions de lancement** : ${PL.actives?`actives ; échec si déplacé avant d’agir : ${PL.verifieeALaResolution?'oui':'non'} ; repli universel si aucune attaque possible : ${PL.repliSiAucune?'oui':'non'}.`:'désactivées.'}\n`;
o+=`- **Setup / debuff** : plafond ±${MO.plafond??2} par stat, effacés au banc : ${MO.reinitialiseAuBanc!==false?'oui':'non'}.\n\n`;
const cs=Object.keys(R.cases).sort((a,b)=>b-a);
o+=`### Report des ciblages sur plateau réduit\n\n`+tbl(['Case visée',...cs.map(n=>`${n} cases`)],L.map(l=>[l,...cs.map(n=>{const Ln=R.cases[n];let i=Ln.indexOf(l);if(i<0){const m=(R.redirection[n]||{})[l];i=Ln.indexOf(m)}return i<0?'—':Ln[i]})]))+'\n';
o+=`## Table des types\n\nLigne = élément de l’attaque, colonne = élément de l’équipement du défenseur.\n\n`+tbl(['Att. ↓ / Déf. →',...ELS.map(e=>`${C.elements[e].glyphe} ${e}`)],ELS.map(a=>[`**${C.elements[a].glyphe} ${a}**`,...ELS.map(d=>{const f=aff(a,d);return f===2?`×${D.multAvantage}`:f===.5?`÷${D.divDesavantage}`:'·'})]))+'\n';
o+=`## Classes\n\n`+tbl(['Classe',...STATS.map(k=>C.stats[k]),'Canal','Équipements','Move pool (défaut en gras)'],Object.entries(C.classes).map(([n,c])=>[`**${n}**`,...STATS.map(k=>c.stats[k]),c.canal,c.equipements.map(e=>C.equipements[e].nom).join(', '),c.movePool.map(id=>(c.parDefaut||[]).includes(id)?`**${C.attaques[id].nom}**`:C.attaques[id].nom).join(', ')]))+'\n';
o+=`## Équipements\n\n`+tbl(['Équipement','Élément','Modificateurs','Classes'],Object.entries(C.equipements).map(([id,E])=>[`**${E.nom}**`,E.element,mods(E.mods),Object.entries(C.classes).filter(([,c])=>c.equipements.includes(id)).map(([n])=>n).join(', ')]))+'\n';
o+=`## Accessoires\n\n`+tbl(['Accessoire','Modificateurs','Effet'],Object.values(C.accessoires).map(A=>[`**${A.nom}**`,mods(A.mods),accFx(A)]))+'\n';
const H=['Attaque','Élément','Classes','Puiss.','Prio.','Cible','Depuis','Effets'];
o+=`## Attaques\n\n`+tbl(H,moveRows(Object.keys(C.attaques).filter(id=>!C.movePoolUniversel.includes(id))))+'\n';
o+=`### Move pool universel\n\n`+tbl(H,moveRows(C.movePoolUniversel))+'\n';
o+=`## Contrôles\n\n`+tbl(['Joueur','Perso gauche','Perso droite','Attaques','Switch'],C.joueurs.map(j=>{const K=j.clavier,k=c=>'`'+c.replace(/^Key|^Digit/,'')+'`';return [j.nom,k(K.gachetteGauche),k(K.gachetteDroite),K.boutons.map(k).join(' '),k(K.switch)]}))+`\nManettes : gâchettes ${C.manette.gachetteGauche}/${C.manette.gachetteDroite}, boutons ${C.manette.nomsBoutons.join(' ')}, switch sur les boutons ${C.manette.switch.join('/')}.\n`;
process.stdout.write(o);
